<?php

/**
 * @file
 */

/**
 * Implements hook_preprocess_html().
 */
function food_delivery_map_preprocess_html(&$variables) {
  $path = \Drupal::service('path.current')->getPath();
  /** @var \Drupal\path_alias\AliasManagerInterface $aliasManager */
  $aliasManager = \Drupal::service('path_alias.manager');
  $path = $alias = $aliasManager->getAliasByPath($path);

  if ($path == '/contact-us') {
    $variables['page']['#attached']['library'][] = 'food_delivery_map/mapbox';
    $variables['page']['#attached']['library'][] = 'food_delivery_map/global_assets';
  }
}
